version: '3'
services:
  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: zato
    restart: always
    command:
      - --shared_buffers=512MB
      - --max_connections=10000
    
  kvdb:
    image: redis
    restart: always
    volumes:
      - redis-data:/data  
  zato:
    image: zato:latest
    volumes:
      - qs-data:/env:rw
      - ./entrypoint.sh:/entrypoint.sh
      - ./services/:/hot-deploy/
      - ./enmase/:/enamss/
      - ./startup.py:/startup.py
      - ./requiremtns.txt:/requiremtns.txt
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    entrypoint: sh /entrypoint.sh
    ports:
      - 8183:8183
      - 11223:11223
      - 17010:17010
    depends_on:
      - db
    restart: always
      
      



volumes:
  db-data:
  redis-data:
  vault-data:
  qs-data:
  


  